# RunIt Config File
# Format: [ItemX]
Name=...
Path=...
Args=...
Hotkey=...

[Item1]
Name=Git Bash
Path=D:\Programs\Git\git-bash.exe
Args=
Hotkey=

[Item2]
Name=Git CMD
Path=C:\Windows\system32\cmd.exe
Args=/K "D:\Tools\Git\cmd\git.cmd" & cd /D "{current_dir}"
Hotkey=

[Item3]
Name=PowerShell
Path=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Args=-NoExit -Command Set-Location '{current_dir}'
Hotkey=

[Item4]
Name=PowerShell 7
Path=
Args=
Hotkey=

[Item5]
Name=Windows Terminal
Path=C:\Users\henrywind\AppData\Local\Microsoft\WindowsApps\wt.exe
Args=-d "{current_dir}"
Hotkey=

[Item6]
Name=CMD
Path=C:\Windows\system32\cmd.exe
Args=/K cd /D "{current_dir}"
Hotkey=

[Item7]
Name=Anaconda PowerShell
Path=C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
Args=-NoExit -Command & 'D:\tools\anaconda3\shell\condabin\conda-hook.ps1'; conda activate 'D:\tools\anaconda3'; Set-Location '{current_dir}'
Hotkey=

[Item8]
Name=Anaconda Prompt
Path=C:\Windows\system32\cmd.exe
Args=/K "D:\tools\anaconda3\Scripts\activate.bat" "D:\tools\anaconda3" & cd /D "{current_dir}"
Hotkey=

[Item9]
Name=VS x64 Native
Path=
Args=
Hotkey=

[Item10]
Name=VS x64_x86 Cross
Path=
Args=
Hotkey=

